### ISSUE TITLE
Not able to launch firefox on mobile browser

### ISSUE THREAD

**Issue by RollerIn** [appium/appium-geckodriver#22] opened 2021-09-03 07:52 UTC
Hello,

**Cap.js**
```
config.capabilities = [
    {
        alwaysMatch: {
            platformName: 'macOS',
            browserName: 'firefox',
            automationName: 'Gecko',
            deviceName: AndroidInfo.deviceName(),
            deviceOrientation:'portriat',
            //'marionette':true,
            'moz:firefoxOptions': {
                androidPackage: 'org.mozilla.firefox',
                //appActivity:"org.mozilla.gecko.BrowserApp",
                androidDeviceSerial: 'EMULATOR30X7X5X0',
                binary: '/Applications/Firefox.app',
                //javascriptEnabled : true
               // "log": {"level": "trace"},
            },
            maxInstances: 1,
            //waitforTimeout: waitforTimeout,
            //commandTimeout: commandTimeout,
            //newCommandTimeout: 30 * 60000,
            acceptInsecureCerts: true

        }
    }
];
exports.config = config;
```

**WDIO.config.js**
```
services: [
        ['firefox-profile'],
        ['geckodriver'],
        ['appium', {
        command: 'appium',
        logFileName: 'appium.log',
        args: {
            relaxedSecurity: true,
            address: host,
            port: port,
            commandTimeout: commandTimeout,
            sessionOverride: true,
            debugLogSpacing: true
        }
    }]],
```
**Error log:**
```
 2021-09-03T07:46:17.701Z ERROR @wdio/utils:shim: TypeError: Cannot read property 'toLowerCase' of undefined
[0-0]     at isFirefox .../node_modules/wdio-geckodriver-service/src/index.js:23:42)
 at GeckoService._mapCapabilities .../node_modules/wdio-geckodriver-service/src/index.js:90:21)
```

```
**what I have observed 
exports.default = class GeckoService {
    constructor (options, capabilities, config) {
        this.config = config
        this.capabilities = capabilities

here capabilities reruns null/undefined object** 
```

where as if I run using chrome as browser..it returns as chrome

can you help in this am I doing anything wrong here or is it issue from GeckoService?

**Comment by jlipps** [comment] 2021-09-03 20:41
I have no idea how WDIO services work, that would be a WDIO thing. It looks like the error you ran into is from WDIO and not this driver.

**Comment by KazuCocoa** [comment] 2021-09-04 00:05
What about adding `appium:` prefix in `alwaysMatch`?
https://github.com/appium/appium-geckodriver#usage

(I agree with jlips's insight about the wdio internal, if you did not have any appium server log)

**Comment by KazuCocoa** [comment] 2021-09-04 19:05
duplicate of https://github.com/appium/appium/issues/15804

**Closed by KazuCocoa** 2021-09-04 19:05 UTC

**Comment by mykola-mokhnach** [comment] 2021-10-17 10:21
To me this looks like a geckodriver issue. I don't thinks there's much we could do about it from Appium side.
